spring:
  application:
    name: stock-manager
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/stock_manager
    username: jaewook
    password: mun1103
  jpa:
    open-in-view: false